apiVersion: v1
name: kafka-operator
version: "0.28.0-adobe-20260622"
description: kafka-operator manages Kafka deployments on Kubernetes
sources:
  - https://github.com/adobe/koperator
appVersion: "0.28.0-adobe-20260622"
