# Default values for kafka-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Lists the secrets you need to use to pull kafka-operator image from a private registry.
imagePullSecrets: []
  # - private-registry-key

operator:
  annotations: {}
  image:
    repository: ghcr.io/banzaicloud/kafka-operator
    tag: ""
    pullPolicy: IfNotPresent
  vaultAddress: ""
  # vaultSecret containing a `ca.crt` key with the Vault CA Certificate
  vaultSecret: ""
  # set of namespaces where the operator watches resources
  namespaces: ""
  verboseLogging: false
  developmentLogging: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceAccount:
    create: true
    name: kafka-operator

webhook:
  enabled: true
  certs:
    generate: true
    secret: "kafka-operator-serving-cert"

certManager:
  namespace: "cert-manager"
  enabled: false

alertManager:
  enable: true

prometheusMetrics:
  enabled: true
  authProxy:
    enabled: true
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.8.0
      pullPolicy: IfNotPresent
    serviceAccount:
      create: true
      name: kafka-operator-authproxy


nameOverride: ""
fullnameOverride: ""

rbac:
  enabled: true

crd:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

## Whether to create the LogForwarding or not.
## Sidecars can be fluent-bit or vector.
## Destinations can be any log analysis and analyzer tools like spluk,Logstash,Datadog etc.
## In this usecase, we are using splunk as destination for logs using fluent-bit sidecar.
## For enabling LogForwarding feature, set the logForward.create to true, then provide the destination splunk and sidecar fluent-bit details.
logForward:
  create: false

## Configuration for the sidecars like fluent-bit or vector with image repository,tag and imagePullSecrets details.
## Configuration for the log analysis and analyzer destinations like pluk,Logstash,Datadog etc
## with host,index,source,logParser,sourceType,port details .
logSidecars: {}
    ## fluentBit: {}
    ##   name: ""
    ##   resources: {}
    ##   port: ""
    ##   image: {}
    ##   destinations: {}
    ##     splunk:
    ##       host: "s"
    ##       source: ""
    ##       index: ""
    ##       logParser: ""
    ##       sourceType: ""
    ##       port: ""
    ##       token: ""
