{
 "title": "Kafka Consumers",
 "tags": [
  "kafka",
  "kafka-minion",
  "consumers"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "kubernetes_namespace", "label": "Namespace", "query": { "query": "kminion_exporter_up" } },
   {
    "name": "kafka_topic",
    "label": "Topic",
    "query": {
     "query": "query_result(sort_desc(count by (topic_name) (kminion_kafka_consumer_group_topic_lag{namespace=\"$kubernetes_namespace\"})))"
    }
   },
   {
    "name": "consumer_group",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kminion_kafka_consumer_group_topic_lag{namespace=\"$kubernetes_namespace\", topic_name=\"$kafka_topic\"}, group_id)"
    }
   },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Topic & Consumer Group Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message Count $kafka_topic",
   "type": "timeseries",
   "description": "Message count is only the difference between all partitions' high and low watermarks. Therefore this count is only an approximation on compact topics",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (topic_name) (kminion_kafka_topic_high_water_mark_sum{namespace=\"$kubernetes_namespace\", topic_name=\"$kafka_topic\"} - kminion_kafka_topic_low_water_mark_sum{namespace=\"$kubernetes_namespace\", topic_name=\"$kafka_topic\"})",
     "legendFormat": "Approx Messages"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka:cluster:partition:isr{namespace=\"$kubernetes_namespace\", topic=\"$kafka_topic\"} > 0)",
     "legendFormat": "total"
    },
    {
     "expr": "max(kminion_kafka_consumer_group_topic_assigned_partitions{namespace=\"$kubernetes_namespace\", topic_name=\"$kafka_topic\", group_id=\"$consumer_group\"})",
     "legendFormat": "subscribed"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "description": "Display the total number of consumers in a consumer group.\nFor multi-topic consumer groups, it also displays the topic_consumers count for the selected topic\nIf there are consumers not assigned to any partition in the consumer group. the count is also displayed",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(kminion_kafka_consumer_group_members{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\"})",
     "legendFormat": "group_consumers"
    },
    {
     "expr": "max(kminion_kafka_consumer_group_empty_members{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\"})",
     "legendFormat": "empty_members"
    },
    {
     "expr": "max(kminion_kafka_consumer_group_topic_members{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\", topic_name=\"$kafka_topic\"})",
     "legendFormat": "topic_consumers"
    }
   ]
  },
  {
   "title": "Consumer Group Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "kminion_kafka_consumer_group_info{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\"}"
    },
    {
     "expr": "avg by (group_id) (kminion_kafka_consumer_group_topic_lag{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\", topic_name=\"$kafka_topic\"})"
    },
    {
     "expr": "count by (group_id) (kminion_kafka_consumer_group_topic_offset_sum{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\"})"
    }
   ]
  },
  {
   "title": "Consumer Group State",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "max by(namespace, group_id, state) (kminion_kafka_consumer_group_info{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\"}) + 1",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Replication Factor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kminion_kafka_topic_info{namespace=\"$kubernetes_namespace\", topic_name=\"$kafka_topic\"}"
    }
   ]
  },
  {
   "title": "Cleanup Policy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kminion_kafka_topic_info{namespace=\"$kubernetes_namespace\", topic_name=\"$kafka_topic\"}"
    }
   ]
  },
  {
   "title": "Consumergroup => Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\", topic_name=\"$kafka_topic\"})",
     "legendFormat": "{{group_id}} => {{topic_name}}"
    }
   ]
  },
  {
   "title": "Topic Lag (messages)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(kminion_kafka_consumer_group_topic_lag{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\", topic_name=\"$kafka_topic\"})"
    }
   ]
  },
  {
   "title": "Consume Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg (sum by (kubernetes_pod_name) (delta(kminion_kafka_consumer_group_topic_offset_sum{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\", topic_name=\"$kafka_topic\"}[90s])/90))"
    }
   ]
  },
  {
   "title": "Messages In vs Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (group_id, topic_name) (sum by (group_id, topic_name, kubernetes_pod_name) (delta(kminion_kafka_consumer_group_topic_offset_sum{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\", topic_name=\"$kafka_topic\"}[90s])/90))",
     "legendFormat": "Consume Rate: {{ group_id }} => {{ topic_name }}"
    },
    {
     "expr": "sum by(topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{namespace=\"$kubernetes_namespace\",topic_name=\"$kafka_topic\"}[$__rate_interval]))",
     "legendFormat": "Produce Rate: {{ topic_name }}"
    }
   ]
  },
  {
   "title": "Lag per Partition: $consumer_group => $kafka_topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (group_id,topic_name,partition_id) (kminion_kafka_consumer_group_topic_partition_lag{namespace=\"$kubernetes_namespace\", group_id=\"$consumer_group\", topic_name=\"$kafka_topic\"})",
     "legendFormat": "Partiton {{partition_id}}"
    }
   ]
  },
  {
   "title": "Partitions Stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (partition) (kafka_log_log_logstartoffset{namespace=\"$kubernetes_namespace\", topic=\"$kafka_topic\"})"
    },
    {
     "expr": "avg by (partition) (kafka_log_log_logendoffset{namespace=\"$kubernetes_namespace\",topic=\"$kafka_topic\"})"
    },
    {
     "expr": "avg by (partition_id) (kminion_kafka_consumer_group_topic_partition_lag{namespace=\"$kubernetes_namespace\",topic_name=\"$kafka_topic\", group_id=\"$consumer_group\"})"
    }
   ]
  },
  { "title": "Cluster Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Topics by number of active consumer groups",
   "type": "table",
   "description": "A consumer group which has at least one non expired consumer group offset for any partition is considered a \"subscriber\" for this topic. This metric can be used to identify topics which may not be consumed by anyone (anymore).",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "count by (topic_name) (kminion_kafka_consumer_group_topic_lag{namespace=\"$kubernetes_namespace\"})>0"
    }
   ]
  },
  {
   "title": "Top 10 Consumer Groups by Consumer Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 37 },
   "targets": [
    {
     "expr": "topk(10, max_over_time(sum by (kubernetes_pod_name, topic_name, group_id) (irate(kminion_kafka_consumer_group_topic_offset_sum{namespace=\"$kubernetes_namespace\"}[3m]))[5m:]) > 0)"
    }
   ]
  },
  {
   "title": "Topics by size",
   "type": "table",
   "description": "Topics by their total size in bytes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "expr": "avg by (topic_name) (kminion_kafka_topic_log_dir_size_total_bytes{namespace=\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Broker Consumers Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker Consumer Incremental Fetch Sessions Evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kafka_server_fetchsessioncache_incrementalfetchsessionevictions_total{namespace=\"$kubernetes_namespace\"}[1m])",
       "legendFormat": "broker-{{brokerId}}"
      }
     ]
    }
   ]
  }
 ]
}