{
 "title": "Kafka Looking Glass",
 "description": "Kafka System Performance",
 "tags": [
  "kafka-operator",
  "kafka"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kafka_server_app_info_version)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(kafka_server_app_info_version{namespace=\"$kubernetes_namespace\"})"
    }
   },
   {
    "name": "kafka_cluster",
    "label": "Kafka cluster",
    "query": {
     "query": "label_values(kafka_server_replicamanager_leadercount{namespace=\"$kubernetes_namespace\"}, canary_cluster)"
    }
   },
   {
    "name": "kafka_broker",
    "label": "Broker",
    "query": {
     "query": "query_result(max_over_time(kafka_server_app_info_version{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"}[${__range_s}s]))"
    }
   },
   {
    "name": "kafka_topic",
    "label": "Topic",
    "query": {
     "query": "query_result(sort_desc((sum_over_time( sum by(topic) (increase(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\".*\",topic!=\"\"}[90s])) [${__range_s}s:90s] ) )+(sum_over_time( sum by(topic) (increase(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\".*\",topic!=\"\"}[90s])) [${__range_s}s:90s] ) ) OR (sum_over_time( sum by(topic) (increase(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\".*\",topic!=\"\"}[90s])) [${__range_s}s:90s] )) OR (sum_over_time( sum by(topic) (increase(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\".*\",topic!=\"\"}[90s])) [${__range_s}s:90s] ) ) ))"
    }
   },
   {
    "name": "kafka_partition",
    "label": "Partition",
    "query": {
     "query": "query_result(kafka:topic_partition_size:count{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\"})"
    }
   },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Canary Producer Throughput",
   "type": "bargauge",
   "description": "A producer produce 1 rps checking that the External Kafka listener is reachable Requires a synthetic canary producer exporting kafka_canary_producer_* metrics; adapt to your own canary tooling or remove this panel.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_canary_producer_record_send_total{cluster=\"$kafka_cluster\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Canary Producer Errors",
   "type": "bargauge",
   "description": "A producer produce 1 rps checking that the External Kafka listener has no errors Requires a synthetic canary producer exporting kafka_canary_producer_* metrics; adapt to your own canary tooling or remove this panel.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_canary_producer_record_error_total{cluster=\"$kafka_cluster\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by(broker_group) (kafka_server_app_info_version{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"})",
     "legendFormat": "{{broker_group}}"
    }
   ]
  },
  {
   "title": "Cluster Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_server_app_info_version{namespace=\"$kubernetes_namespace\"}"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "description": "Number of topics in cluster",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum(kafka:cluster:partition:replicascount{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}>0) by (topic))"
    }
   ]
  },
  {
   "title": "Unclean Leader Election",
   "type": "stat",
   "description": "Replicas that are online",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_controller_controllerstats_uncleanleaderelections_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Envoy Unhealthy Kafka",
   "type": "stat",
   "description": "Number of unhealthy kafka nodes in envoy proxy Only applicable if external access is exposed through an Envoy proxy in front of the brokers.",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{namespace=\"$kubernetes_namespace\"})  - sum(envoy_cluster_membership_healthy{namespace=\"$kubernetes_namespace\"}))"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that don?t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Partitions at mininimum ISR",
   "type": "stat",
   "description": "Number of partitions which are at their minimum in sync replica count (| ISR | == | min.insync.replicas |).",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka:cluster:partition:atminisr{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Partitions under mininimum ISR",
   "type": "stat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |).",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka:cluster:partition:underminisr{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Envoy Instances",
   "type": "stat",
   "description": " Only applicable if external access is exposed through an Envoy proxy in front of the brokers.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(broker_group) (envoy_server_live{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"})",
     "legendFormat": "{{broker_group}}"
    }
   ]
  },
  {
   "title": "ZK Quorum Size",
   "type": "stat",
   "description": "Number of Zookeeper peers",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(quorum_size{namespace=\"$kubernetes_namespace\", job=~\".+-headless\"})"
    }
   ]
  },
  {
   "title": "ZK Leaders",
   "type": "stat",
   "description": "Number of Zookeeper leaders in the cluster. It should always be 1",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(leader_uptime{namespace=\"$kubernetes_namespace\", job=~\".+-headless\"})"
    }
   ]
  },
  {
   "title": "ZK digest mismatches",
   "type": "stat",
   "description": "This should be 0 or No Data. If > 0 then a zk pod is out of sync with the cluster.",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "digest_mismatches_count{namespace=\"$kubernetes_namespace\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Online Replicas",
   "type": "stat",
   "description": "Replicas that are online",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Kafka Disk Capacity",
   "type": "stat",
   "description": "Total remaining capacity in Kafka",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=\"$kubernetes_namespace\",persistentvolumeclaim=~\"$cluster_name.*\"})",
     "legendFormat": "Remaining"
    },
    {
     "expr": "sum by(cluster ) (label_replace(kubelet_volume_stats_capacity_bytes{namespace=\"$kubernetes_namespace\", persistentvolumeclaim=~\"$cluster_name.*\"}, \"cluster\", \"$1\", \"persistentvolumeclaimi\", \"(.+)-([0-9]+)-storage-.*\"))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Reassigning Partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_reassigningpartitions{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"})"
    }
   ]
  },
  {
   "title": "CC Unfixable Goals",
   "type": "stat",
   "description": "CruiseControl unfixable goals requires manual intervention to Kafka. Check CC to see what goal fails to be self-healed",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_cruisecontrol_anomalydetector_goal_violation_has_unfixable_goals_value{namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "Unfixable Goals"
    }
   ]
  },
  {
   "title": "Consumer Groups",
   "type": "stat",
   "description": "Total number of consumer groups in cluster",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(kminion_kafka_consumer_group_info_count{namespace=\"$kubernetes_namespace\"})"
    }
   ]
  },
  { "title": "Topic Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "IN messages during interval",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum_over_time( sum by(topic) (increase(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\".*\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\"}[3m])) [${__range_s}s:3m] ) > 0\n",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "IN Size during interval",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum_over_time( sum by(topic) (increase(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\".*\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\"}[90s])) [${__range_s}s:90s] ) > 0",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "OUT Size during interval",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum_over_time( sum by(topic) (increase(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\".*\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\"}[90s])) [${__range_s}s:90s] ) > 0",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topics by size",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka:log:size:topic:broker{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"}) > 0"
    }
   ]
  },
  {
   "title": "Topics by no of partitions",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kminion_kafka_topic_info_partitions_count{namespace=\"$kubernetes_namespace\"}) by (topic_name)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topics by replication lag",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_server_fetcherlagmetrics_consumerlag{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\".*\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\"}) by (topic) > 0",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Cluster Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Incoming Byte Rate",
   "type": "stat",
   "description": "Total Incoming Byte Rate",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\"}[90s]))"
    }
   ]
  },
  {
   "title": "Total Incoming Rates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\"}[90s]))",
     "legendFormat": "Produce Message Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\"}[90s]))",
     "legendFormat": "Produce Request Rate"
    }
   ]
  },
  {
   "title": "Total Cluster Replication Rate",
   "type": "stat",
   "description": "Replication IN + OUT across the entire cluster",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_replicationbytesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}[90s])) + sum(rate(kafka_server_brokertopicmetrics_replicationbytesout_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}[90s]))"
    }
   ]
  },
  {
   "title": "Total Outgoing Byte Rate",
   "type": "stat",
   "description": "Total Outgoind Byte Rate",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\"}[90s]))"
    }
   ]
  },
  {
   "title": "Total Fetch Request Rate",
   "type": "stat",
   "description": "Total Produce Request Rate",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\"}[90s]))"
    }
   ]
  },
  {
   "title": "Message Conversion Rate",
   "type": "stat",
   "description": "Message Conversations performed by broker due to message protocol mismatch on client side.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_producemessageconversions_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}[90s]))",
     "legendFormat": "produce"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_fetchmessageconversions_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}[90s]))",
     "legendFormat": "consume"
    }
   ]
  },
  {
   "title": "Byte Rate Per Second",
   "type": "timeseries",
   "description": "Broker traffic excluding replication",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\",topic=~\"$kafka_topic\", topic!=\"\"}[1m])) by (brokerId)",
     "legendFormat": "in-{{brokerId}}"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\",topic=~\"$kafka_topic\", topic!=\"\"}[1m]))  by (brokerId)",
     "legendFormat": "out-{{brokerId}}"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "IN-Total"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "OUT-Total"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\",topic=~\"$kafka_topic\",topic!=\"\"}[1m])) by (brokerId)",
     "legendFormat": "{{brokerId}}"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m])) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Replication Lag ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_fetcherlagmetrics_consumerlag{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\", partition=~\"$kafka_partition\"}) by (brokerId,topic,partition) > 0",
     "legendFormat": "{{brokerId}}:{{topic}}:{{partition}}"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "timeseries",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\",topic=~\"$kafka_topic\",topic!=\"\"}[1m])) by (brokerId)",
     "legendFormat": "{{brokerId}}"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\",topic=~\"$kafka_topic\",topic!=\"\"}[1m])) by (brokerId) > 0",
     "legendFormat": "failed-{{brokerId}}"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "timeseries",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\",topic=~\"$kafka_topic\",topic!=\"\"}[1m])) by (brokerId)",
     "legendFormat": "{{brokerId}}"
    },
    {
     "expr": "  sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\",topic=~\"$kafka_topic\",topic!=\"\"}[1m])) by (brokerId) > 0",
     "legendFormat": "failed-{{brokerId}}"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cruise Control Auto Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(max_over_time(kafka_cruisecontrol_executor_replica_action_completed_value{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-cruisecontrol-.+\"}[$__interval])>0)",
     "legendFormat": "replicas_move_completed"
    },
    {
     "expr": "(max_over_time(kafka_cruisecontrol_executor_leadership_action_completed_value{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-cruisecontrol-.+\"}[$__interval])>0)",
     "legendFormat": "leadership_move_completed"
    },
    {
     "expr": "(max_over_time(kafka_cruisecontrol_executor_intra_broker_replica_action_completed_value{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-cruisecontrol-.+\"}[$__interval])>0)",
     "legendFormat": "intra_broker_replica_move_completed"
    },
    {
     "expr": "-1 * (kafka_cruisecontrol_anomalydetector_goal_violation_has_unfixable_goals_value{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-cruisecontrol-.+\"} > 0)",
     "legendFormat": "has_unfixable_goals"
    },
    {
     "expr": "max_over_time ( sum by (namespace) (changes(kafka_cruisecontrol_anomalydetector_goal_violation_rate_count{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-cruisecontrol-.+\"}[90s]))[10m:10s]) > 0\n",
     "legendFormat": "goal-violations"
    },
    {
     "expr": "max_over_time ( sum by (namespace) (changes(kafka_cruisecontrol_anomalydetector_broker_failure_rate_count{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-cruisecontrol-.+\"}[90s]))[10m:10s]) > 0\n",
     "legendFormat": "broker-failure"
    }
   ]
  },
  {
   "title": "Envoy connections",
   "type": "timeseries",
   "description": "In the positive Y, number of active connections, in the negative Y, number of overflowing connections. The later should be 0. Only applicable if external access is exposed through an Envoy proxy in front of the brokers.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name)(envoy_cluster_upstream_cx_active{namespace=\"$kubernetes_namespace\", envoy_cluster_name=~\"broker.*\"})",
     "legendFormat": "active-{{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name)(envoy_cluster_upstream_cx_overflow{namespace=\"$kubernetes_namespace\",envoy_cluster_name=~\"broker.*\"}) * -1 < 0",
     "legendFormat": "overflow-{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Unbalanced disks in kafka cluster",
   "type": "table",
   "description": "Shows the disk in cluster which are over-used - (size wise) compared to avg on that broker",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 43 },
   "targets": [
    {
     "expr": "sum by(broker,persistentvolumeclaim) (label_replace ( (kubelet_volume_stats_available_bytes{namespace=\"$kubernetes_namespace\",persistentvolumeclaim=~\"$cluster_name.*\"}), \"broker\", \"$1\", \"persistentvolumeclaim\", \"$cluster_name-([0-9]+)-.+\"))\n\n  < on (broker) group_left()\n\n  (\n0.8 * avg by (broker)(sum by(broker,persistentvolumeclaim) (label_replace ( (kubelet_volume_stats_available_bytes{namespace=\"$kubernetes_namespace\",persistentvolumeclaim=~\"$cluster_name.*\"}), \"broker\", \"$1\", \"persistentvolumeclaim\", \"$cluster_name-([0-9]+)-.+\")))\n\n  )"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(brokerId, error) (rate(kafka_network_requestmetrics_errors_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",error!=\"NONE\"}[3m])) > 0",
     "legendFormat": "req-errors-{{brokerId}}-{{error}}"
    },
    {
     "expr": "sum by (brokerId,topic) (rate(kafka_server_brokertopicmetrics_failedfetchrequests_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",pod=~\"$cluster_name-($kafka_broker)\"}[3m])) > 0",
     "legendFormat": "failed-fetches-{{brokerId}}:{{topic}}"
    },
    {
     "expr": "sum by(brokerId) (rate(kafka_server_replica_fetcher_metrics_connection_close_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"}[3m])) > 0",
     "legendFormat": "fetch-failed-connections-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Reassigning Partitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_reassigningpartitions{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}) by (brokerId) > 0",
     "legendFormat": "{{brokerId}}"
    }
   ]
  },
  {
   "title": "Authorization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Authorizer Token Validations",
     "type": "table",
     "description": " Requires a custom Kafka authorizer plugin that exports JMX metrics under the kafka_authorizer_* names used here; adjust the metric prefix/labels to match your authorizer, or remove this panel if you use Kafka's default authorizer.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum_over_time(sum by (client_id) (increase(kafka_authorizer_valid_token_count{namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[90s]))[${__range_s}s:90s] ) > 0",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Unauthorized requests per principal",
     "type": "table",
     "description": " Requires a custom Kafka authorizer plugin (see kafka_authorizer_* metrics); remove if not applicable.",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "sum_over_time(sum by (principal,resourceType) (increase(kafka_authorizer_unauthorized_count{namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[90s]))[${__range_s}s:90s] ) > 0",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Unauthorized total requests",
     "type": "timeseries",
     "description": " Requires a custom Kafka authorizer plugin (see kafka_authorizer_* metrics); remove if not applicable.",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(kafka_authorizer_unauthorized_total_count{namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[1m])>0",
       "legendFormat": "{{brokerId}}-{{resourceType}}"
      }
     ]
    },
    {
     "title": "Authorized total requests",
     "type": "timeseries",
     "description": " Requires a custom Kafka authorizer plugin (see kafka_authorizer_* metrics); remove if not applicable.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (brokerId) (rate(kafka_authorizer_authorized_total_count{namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[1m]))",
       "legendFormat": "{{brokerId}}"
      },
      {
       "expr": "sum(rate(kafka_authorizer_authorized_total_count{namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Authorized topic requests",
     "type": "timeseries",
     "description": " Requires a custom Kafka authorizer plugin (see kafka_authorizer_* metrics); remove if not applicable.",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (brokerId) (rate(kafka_authorizer_authorized_service_count{resourceType=\"topic\",namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[1m]))",
       "legendFormat": "service"
      },
      {
       "expr": "sum by (brokerId) (rate(kafka_authorizer_authorized_anonymous_count{resourceType=\"topic\",namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[1m]))",
       "legendFormat": "user-anonymous"
      }
     ]
    },
    {
     "title": "Authorized consumer group requests",
     "type": "timeseries",
     "description": " Requires a custom Kafka authorizer plugin (see kafka_authorizer_* metrics); remove if not applicable.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (brokerId) (rate(kafka_authorizer_authorized_service_count{resourceType=\"group\",namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[1m]))",
       "legendFormat": "service"
      },
      {
       "expr": "sum by (brokerId) (rate(kafka_authorizer_authorized_anonymous_count{resourceType=\"group\",namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[1m]))",
       "legendFormat": "user-anonymous"
      }
     ]
    },
    {
     "title": "Authorized cluster requests",
     "type": "timeseries",
     "description": " Requires a custom Kafka authorizer plugin (see kafka_authorizer_* metrics); remove if not applicable.",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (brokerId) (rate(kafka_authorizer_authorized_service_count{resourceType=\"cluster\",namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[1m]))",
       "legendFormat": "service"
      },
      {
       "expr": "sum by (brokerId) (rate(kafka_authorizer_authorized_anonymous_count{resourceType=\"cluster\",namespace=\"$kubernetes_namespace\", kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[1m]))",
       "legendFormat": "user-anonymous"
      }
     ]
    }
   ]
  },
  { "title": "Brokers Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Aggregated Kafka Broker Pods CPU Usage",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-($kafka_broker)\",container=\"kafka\", resource=\"cpu\"}))",
     "legendFormat": "kafka pod cpu limit"
    },
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\"}[1m])",
     "legendFormat": "used-{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "description": "Kafka Broker Pods Memory Usage",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-($kafka_broker)\",container=\"kafka\"}) by (pod)",
     "legendFormat": "used-{{pod}}"
    },
    {
     "expr": "min(sum (kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$kubernetes_namespace\", resource=\"memory\", pod=~\"$cluster_name-($kafka_broker)\", container=~\"kafka\"}) by(pod,container))",
     "legendFormat": "max-mem"
    },
    {
     "expr": "process_resident_memory_bytes{namespace=\"$kubernetes_namespace\",  pod=~\"$cluster_name-($kafka_broker)\", brokerId=~\".+\"}\t",
     "legendFormat": "rss-{{pod}}"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "timeseries",
   "description": "Kafka Broker Pods Available Disk Space",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=\"$kubernetes_namespace\",persistentvolumeclaim=~\".*kafka.*\"}) / (sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$kubernetes_namespace\",persistentvolumeclaim=~\".*kafka.*\"}))",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk Usage (Broker distribution)",
   "type": "timeseries",
   "description": "Kafka Broker Pods Disk Usage (Aggregated by broker)",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (broker_id) (label_replace(kubelet_volume_stats_used_bytes{namespace=\"$kubernetes_namespace\",persistentvolumeclaim=~\".*kafka.*\"}, \"broker_id\", \"$1\",\"persistentvolumeclaim\", \"(.+)-storage(.*)\"))",
     "legendFormat": "{{broker_id}}"
    },
    {
     "expr": "min(sum by (broker_id)\n(label_replace(\nkubelet_volume_stats_capacity_bytes{namespace=\"$kubernetes_namespace\", persistentvolumeclaim=~\"$cluster_name.*\"}\n,\"broker_id\", \"$1\",\"persistentvolumeclaim\", \"(.+)-storage(.*)\")))",
     "legendFormat": "Broker Total Storage"
    }
   ]
  },
  {
   "title": "Available Disk Space (Zookeeper)",
   "type": "timeseries",
   "description": "Zookeeper Pods Disk Usage",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=\"$kubernetes_namespace\",persistentvolumeclaim=~\".*zookeeper.*\"}) / ( sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$kubernetes_namespace\",persistentvolumeclaim=~\".*zookeeper.*\"}))",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Network and Handlers Usage",
   "type": "timeseries",
   "description": "network and io/handlers pools usage",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (kafka_network_socketserver_networkprocessoravgidle_percent{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}*100)",
     "legendFormat": "network-{{brokerId}}"
    },
    {
     "expr": "100-irate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}[1m])/10000000 > 0",
     "legendFormat": "handlers-{{brokerId}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-($kafka_broker)\",kafka_cr=\"$cluster_name\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-($kafka_broker)\",kafka_cr=\"$cluster_name\"}[1m])) by (pod,gc) > 0",
     "legendFormat": "{{pod}} - {{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Rate (GC/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-($kafka_broker)\",kafka_cr=\"$cluster_name\"}[1m])) by (pod,gc) > 0",
     "legendFormat": "{{pod}} - {{gc}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors Pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-($kafka_broker)\",kafka_cr=\"$cluster_name\"}/java_lang_operatingsystem_maxfiledescriptorcount{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-($kafka_broker)\",kafka_cr=\"$cluster_name\"}",
     "legendFormat": "{{app}}-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Broker Disk Write Throughput",
   "type": "timeseries",
   "description": "Kafka Broker Disk Write Throughput",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(kafka_server_kafkaserver_linux_disk_write_bytes{namespace=\"$kubernetes_namespace\"}[3m])",
     "legendFormat": "broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Broker Disk Read Throughput",
   "type": "timeseries",
   "description": "Kafka Broker Disk Read Throughput",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(kafka_server_kafkaserver_linux_disk_read_bytes{namespace=\"$kubernetes_namespace\"}[3m])",
     "legendFormat": "broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Topic Size per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(30, kafka:log:size:topic:broker{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",topic=~\"$kafka_topic\"})",
     "legendFormat": "{{brokerId}}:{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Segments #",
   "type": "graph",
   "description": "Top 10 topics wrt to number of segments per broker",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(30, kafka:log:numlogsegments{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\",topic=~\"$kafka_topic\"})",
     "legendFormat": "{{brokerId}}::{{topic}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Broker Produce time ms (p.999)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"Produce\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}",
     "legendFormat": "q{{brokerId}}"
    }
   ]
  },
  {
   "title": "Broker FetchConsumer time ms (p.999)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}",
     "legendFormat": "{{brokerId}}"
    }
   ]
  },
  {
   "title": "Broker FetchFollower time ms (p.999)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}",
     "legendFormat": "q{{brokerId}}"
    }
   ]
  },
  {
   "title": "Broker Produce Request Time Breakdown (p.999)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems{request=\"Produce\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}>0",
     "legendFormat": "{{brokerId}}-req-queue"
    },
    {
     "expr": "kafka_network_requestmetrics_localtimems{request=\"Produce\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}>0",
     "legendFormat": "{{brokerId}}-req-local"
    },
    {
     "expr": "kafka_network_requestmetrics_remotetimems{request=\"Produce\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}>0",
     "legendFormat": "{{brokerId}}-req-remote"
    },
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems{request=\"Produce\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}>0",
     "legendFormat": "{{brokerId}}-resp-queue"
    },
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{request=\"Produce\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}>0",
     "legendFormat": "{{brokerId}}-resp-send"
    }
   ]
  },
  {
   "title": "Broker Consume Request Time Breakdown (p.999)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems{request=\"FetchConsumer\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}>0",
     "legendFormat": "{{brokerId}}-req-queue"
    },
    {
     "expr": "kafka_network_requestmetrics_localtimems{request=\"FetchConsumer\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}>0",
     "legendFormat": "{{brokerId}}-req-local"
    },
    {
     "expr": "kafka_network_requestmetrics_remotetimems{request=\"FetchConsumer\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}>0",
     "legendFormat": "{{brokerId}}-req-remote"
    },
    {
     "expr": "kafka_network_requestmetrics_responsequeuetimems{request=\"FetchConsumer\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}>0",
     "legendFormat": "{{brokerId}}-resp-queue"
    },
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{request=\"FetchConsumer\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\", quantile=\"0.999\"}>0",
     "legendFormat": "{{brokerId}}-resp-send"
    }
   ]
  },
  {
   "title": "Replication Rate Per Second",
   "type": "timeseries",
   "description": "Replication Rate Per Second",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_replicationbytesin_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}[1m])) by (brokerId)",
     "legendFormat": "in-{{brokerId}}"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_replicationbytesout_total{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}[1m])) by (brokerId)",
     "legendFormat": "out-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(kafka:cluster:broker:topic:urp{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",kafka_cr=\"$cluster_name\", pod=~\"$cluster_name-($kafka_broker)\", topic=~\"$kafka_topic\"}) by (namespace,kafka_cr,brokerId)) ",
     "legendFormat": "{{brokerId}}"
    }
   ]
  },
  {
   "title": "Broker Flush Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_log_logflushstats_logflushrateandtimems{quantile=\"0.999\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}) by (brokerId)",
     "legendFormat": "{{brokerId}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{namespace=\"$kubernetes_namespace\",pod=~\"$cluster_name-($kafka_broker)\",kafka_cr=\"$cluster_name\"}",
     "legendFormat": "{{app}}-{{brokerId}}-{{state}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker ZK Request Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{quantile=\"0.999\", namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}) by (brokerId)",
       "legendFormat": "{{brokerId}}"
      }
     ]
    },
    {
     "title": "Offline broker disks",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 94 },
     "targets": [
      {
       "expr": "kafka_log_logmanager_logdirectoryoffline{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\",pod=~\"$cluster_name-($kafka_broker)\"}>0",
       "legendFormat": "Broker:{{brokerId}} Disk:{{logDirectory}}"
      }
     ]
    },
    {
     "title": "Kafka Topics With Orphan Replicas (Space Waste)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka:topic_orphan_replicas_size{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Kafka Topics With Orphan Replicas (Partition Count)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka:topic_orphan_replicas_count{namespace=\"$kubernetes_namespace\",kafka_cr=\"$cluster_name\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  }
 ]
}