name: build-publish-docker-image

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Get tag name
        id: vars
        run: echo "tag=${GITHUB_REF:10}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ !startsWith( steps.vars.outputs.tag, 'kafka-' ) }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ !startsWith( steps.vars.outputs.tag, 'kafka-' ) }}
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VERSION=${{ steps.vars.outputs.tag }}
            GIT_SHA=${{ github.sha }}
          tags: adobe/kafka-operator:${{ steps.vars.outputs.tag }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
